# Generated by Django 5.0.7 on 2024-07-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_watchedb_delete_watches'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='watch_images/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
