# Generated by Django 5.0.7 on 2024-07-25 10:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reviews',
            new_name='Watchreviews',
        ),
    ]
