# Generated by Django 5.0.7 on 2024-08-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0008_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
    ]
