# Generated by Django 4.2.15 on 2024-08-31 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0013_alter_cartitems_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='users',
        ),
    ]
