# Generated by Django 4.2.15 on 2024-08-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0014_rename_user_cart_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='users',
            new_name='user',
        ),
    ]
