# Generated by Django 4.2.15 on 2024-09-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0017_alter_cartitems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='product',
            field=models.ManyToManyField(to='Homepage.watchupload'),
        ),
    ]
