# Generated by Django 4.2.15 on 2025-01-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0019_remove_cartitems_product_cartitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchupload',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.watchupload'),
        ),
    ]
